// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:cc990b57-a91d-4845-9d98-587497a93aaa',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'reacttodo-hosting-mobilehub-1302164788',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd2mmmx4ka4ogra.cloudfront.net',
aws_mobile_analytics_app_id : 'eaf60bd62dcc498f86a6f48428809181',
aws_project_id : 'ecf6aa97-530d-47c3-8a3b-140d03918edd',
aws_project_name : 'react-todo',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'reacttodo-mobilehub-1302164788',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});